/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_yuvwatermark_YuvWaterMarkJni */

#ifndef _Included_com_android_yuvwatermark_YuvWaterMarkJni
#define _Included_com_android_yuvwatermark_YuvWaterMarkJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    startYuvWaterEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_startYuvWaterEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    Yv12ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_Yv12ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    I420ToYv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_I420ToYv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    Nv21ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_Nv21ToI420
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    I420ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_I420ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    Nv21ToNv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_Nv21ToNv12
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    Nv12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_Nv12ToNv21
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    yuvAddWaterMark
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_yuvAddWaterMark
  (JNIEnv *, jclass, jlong, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_android_yuvwatermark_YuvWaterMarkJni
 * Method:    stopYuvWaterEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_yuvwatermark_YuvWaterMarkJni_stopYuvWaterEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
